server:
  port: 15460

spring:
  datasource:
    url: jdbc:postgresql://13.124.48.253:9030/postgres
    username: postgres
    password: test0309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: file:${STATIC_FILE_PATH:C:/dev/uploaded/}
      add-mappings: true

  servlet:
    multipart:
      max-file-size: 25000MB
      max-request-size: 25000MB

file:
  video-path: ${VIDEO_PATH:C:/dev/uploaded/video/}
  image-path: ${IMAGE_PATH:C:/dev/uploaded/image/}