server:
  port: 15460

spring:
  datasource:
    url: jdbc:postgresql://13.124.48.253:9030/postgres
    username: postgres
    password: test0309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: file:${STATIC_FILE_PATH:./uploaded/}

  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB

file:
  video-path: ${VIDEO_PATH:./uploaded/video/}
  image-path: ${IMAGE_PATH:./uploaded/image/}